### ISSUE TITLE
Sensitive Information (Firebase ID and Other Details) Exposed on GitHub

### ISSUE THREAD

**Issue by ArchanRD** [ankit071105/Ticket-Booking#186]
It appears that the Firebase ID and other sensitive details are currently exposed in the repository, which is not a secure practice. To protect sensitive data, I recommend creating a `.env` file to store this information securely.

## Task
- [ ] Remove the Firebase ID and any other sensitive information from the public repository.
- [ ] Implement a .env file to store environment-specific variables such as Firebase credentials.
- [ ] Update the codebase to load these variables securely using the .env file.
- [ ] Document the process for setting up the .env file in the project README.

Doing this sensitive information should no longer be exposed in the repository. The code should reference environment variables stored in a .env file for secure access to Firebase and other configurations.

I would like to work on this issue under gssoc-ext and hacktoberfest.

**Comment by ankit071105** [comment]
@riyaaryan2004  Solve this issue

**Comment by riyaaryan2004** [comment]
@ankit071105 okay

**Comment by riyaaryan2004** [comment]
@ankit071105  This is a non-React app 
I am not able to fix this issue for client side.
I would have been possible if it was react based project.
Since you are using vercel for project deployment , you can use environment variable there for credential hiding.
